### PR TITLE
Blocks: Blocks assembly generator

### PR DESCRIPTION
**Pull request by kanishkan**
Converts tpef to pasm, Blocks assembly.
Translation is limited to VLIW mode, and instruction
in the ADF is expected to match with Blocks ISA.

### CODE REVIEW

**Comment by kanishkan** [comment]
In-progress.
TODO:
- [ ] Add unit test
- [ ] Verify output with Blocks RTL simulator

**Comment by pjaaskel** [comment]
Is this still in-progress or ready for merge review?

**Comment by kanishkan** [comment]
I have some local changes. So, it is not yet ready.

**Comment by kanishkan** [comment]
This is ready for review.

**Pull request merged**
