### PR TITLE
added 3.8.1 script

### PR DESCRIPTION
**Pull request by jfmherokiller**
added a script that builds llvm version 3.8.1 with patches applied

### CODE REVIEW

**Comment by jfmherokiller** [comment]
sorry for the double pull request i got caught in rebase hell

**Comment by pjaaskel** [comment]
Is this script really useful? The default installer checks out the RELEASE_38 branch which should include all fixes in 3.8.1 (and possibly others done after that) to my understanding?

**Comment by jfmherokiller** [comment]
well from what i was able to learn by compiling all the toolchains from source 3.8 does not include fixes from 3.8.1 and can sometimes segfault during compilation as seen [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/166952186/log.txt) 
screen shot 2016-10-12 at 1 06 20 pm

**Comment by pjaaskel** [comment]
Yes, but it checks out the release branch which should get the fixes for the point releases backported. Or has that changed?

**Comment by pjaaskel** [comment]
This is outdated.

**Pull request closed without merging**
