### PR TITLE
Endianness stuff

### PR DESCRIPTION
**Pull request by alexhrv**
- Added some information on how to add freshly installed LLVM libraries to search path (#60)
- LE is now used by default in ADF/MOM (#61)

### CODE REVIEW

**Comment by pjaaskel** [comment]
I think bunch of unit tests fail now. Please run compiletest.sh -q. Or 'make test' in test.

**Comment by tervoa** [comment]
The ADF version number needs to be bumped with this PR, as machines without the endianess tag are handled differently.

**Comment by pjaaskel** [comment]
Ah, it was not the intention here. The ADF format should remain the same, only Machine's default should change (so when serialized, it will end up having the little-endian tag).

**Comment by pjaaskel** [comment]
After pulling this in, at least some of the unit tests fail. Please see the above comment: the ADF default (no tag, assume BE) should remain, but new machines should be created with LE by default. That is visible in new Machine objects and in ProDe.

**Pull request merged**
